version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: proyecto_tsic2
      MYSQL_USER: root
      MYSQL_PASSWORD: Mysql123
      MYSQL_ROOT_PASSWORD: Mysql123
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: proyectosfi
    container_name: proyectosfi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

networks:
  laravel: